name: 'monotools/semver-yeasy'
description: 'Semver Versioning made easy'
inputs:
  repo-type:
    description: 'which mode to run'
    required: true
    default: 'changed'
  mode:
    description: 'the type of repo - "MONOREPO" or "SINGLE_APP"'
    required: true
    default: 'changed'
outputs:
  tag:
    description: 'The tags to be made for this current commit'
runs:
  using: 'docker'
  image: 'dockerfile'
  env:
    GITVERSION_EXEC_PATH: /root/.dotnet/tools/dotnet-gitversion
  args:
    - ${{ inputs.mode }}
    - ${{ inputs.repo-type }}