name: 'monotools/semver-yeasy'
description: 'Semver Versioning made easy'
inputs:
  repo-type:
    description: 'which mode to run'
    required: true
  mode:
    description: 'the type of repo - "MONOREPO" or "SINGLE_APP"'
    required: true
runs:
  using: 'composite'
  steps:
  - run: ${{ github.action_path }}/test/script.sh ${{ inputs.mode }} ${{ inputs.repo-type }}
    shell: bash
    env:
      GITVERSION_EXEC_PATH: /root/.dotnet/tools/dotnet-gitversion
