name: 'monotools/semver-yeasy'
description: 'Semver Versioning made easy'
inputs:
  repo-type:
    description: 'which mode to run'
    required: true
  mode:
    description: 'the type of repo - "MONOREPO" or "SINGLE_APP"'
    required: true
  DIFF_SOURCE:
    description: 'the source ref of the changes to be processed'
    required: false
  DIFF_DEST:
    description: 'the destination ref of the changes to be processed'
    required: false
outputs:
  changed_services:
    description: "Changed services between diff_source and diff_dest"
    value: ${{ steps.versioning.outputs.changed_services }}
  PR_BODY:
    description: "PR Body text to describe services changed between diff_source and diff_dest"
    value: ${{ steps.versioning.outputs.PR_BODY }}
  diff_source:
    description: ""
    value: ${{ steps.versioning.outputs.diff_source }}
  diff_dest:
    description: ""
    value: ${{ steps.versioning.outputs.changed_services }}
runs:
  using: 'composite'
  steps:
  - id: versioning
    env:
      DIFF_SOURCE: ${{ inputs.diff_source }}
      DIFF_DEST: ${{ inputs.diff_dest }}
    run: bash ${{ github.action_path }}/semver-yeasy.sh ${{ inputs.mode }} ${{ inputs.repo-type }}
    shell: bash
