# Container image that runs your code
FROM mcr.microsoft.com/dotnet/runtime-deps:7.0

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY semver-yeasy.sh /semver-yeasy.sh

# Code file to execute when the docker container starts up (`semver-yeasy.sh`)
ENTRYPOINT ["bash", "/semver-yeasy.sh"]
