mode: MainLine
tag-prefix: '[vV]?'
branches:
  main:
    increment: Patch
  release:
    increment: None
  feature:
    regex: ^(feat|fix|improv|chore)[/-]
    increment: Patch
  hotfix:
    tag: hotfix
    increment: Patch
